Add namespace for service-account.yaml
CircleCI-Public/container-runner-helm-chart pull request #58
Opened 2024-06-18 23:59 UTC by carlochessamp

:gear: **Issue**

*Ticket/s*:   

:gear: **Change** 

I have added the namespace metadata to an object

Change Type: 

AC:

:white_check_mark: **Fix**

:question: **Tests**

- [ ] Tests for new feature and update for changes
- [ ] Linting passes and/or formatting matches the standard of the repo

🗒️ **Documentation**

- [ ] Updated related documentation (if applicable).
- [ ] Updated Change log (if exists)

2024-06-24 20:25 UTC, carlochessamp commented
Hello @Stuart133 I have this little fix for the helm chart

2024-07-09 17:52 UTC, ryanwohara commented
@carlochessamp Thank you for the contribution. Can you help us understand in which circumstance this is required? We'd like to fully understand it, if only for documentation for the next release.

2024-07-12 14:13 UTC, carlochessamp commented
@ryanwohara recently I was deploying this helm chart in a k8s cluster where the Circleci Container runner wasn't deployed to the default namespace later I notice that the service account was missing because it was created on the default namespace that the reason I'm suggestion to specify the service account namespace in the template :D

2024-07-12 16:49 UTC, atulsingh0 approved these changes

2024-07-12 18:25 UTC, ryanwohara commented
@carlochessamp Can you share the install command you ran? Perhaps there is a problem with our docs?

2024-07-12 22:01 UTC, carlochessamp commented
> @carlochessamp Can you share the install command you ran? Perhaps there is a problem with our docs?

I can't remember. It was done using terraform-helm integration resource so I don't have the details of that execution

2024-07-15 09:25 UTC, christian-stephen requested changes

2024-07-15 09:25 UTC, christian-stephen commented on templates/service-account.yaml
> +    namespace: {{ $namespace }}
```suggestion
metadata:
  name: {{ .Values.logging.serviceAccount.secret.name }}
  namespace: {{ $namespace }}
```

2024-07-16 10:22 UTC, christian-stephen approved these changes

2024-08-31 14:24 UTC, carlochessamp commented
Hello guys! friendly ping about this PR :D @christian-stephen @atulsingh0

2024-10-10 14:59 UTC, merged

2024-10-10 14:59 UTC, jrahme-cci commented
Sorry for the delay @carlochessamp , I just pushed a changelog entry to your branch and will get this merged now.